language: node_js
node_js:
  - "6.3.1"

addons:
  apt:
    packages:
      - xvfb
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

env:
  CXX=g++-4.8

before_install:
  - npm install -g npm@latest

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - npm run dev
